### PR TITLE
Add MicK7 as maintainer

### PR DESCRIPTION
**Pull request by mdpiper**
This PR adds @MicK7 as a maintainer. Bumped the build number.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mdpiper** [comment]
Hi @MicK7 -- Yeah, there's little work involved; just checking over the changes when a version is incremented. I haven't used CGNS is a few years, so I feel kinda bad about being the only maintainer. I think you have to acknowledge that you're willing to be a maintainer in order for this PR to be merged.

**Comment by mdpiper** [comment]
@conda-forge-admin, please rerender

**Comment by MicK7** [comment]
> 
> 
> Hi @MicK7 -- Yeah, there's little work involved; just checking over the changes when a version is incremented. I haven't used CGNS is a few years, so I feel kinda bad about being the only maintainer. I think you have to acknowledge that you're willing to be a maintainer in order for this PR to be merged.

Ok I am willing to be a maintainer

**Comment by mdpiper** [comment]
@MicK7 Awesome, thanks!

**Pull request merged**
