### PR TITLE
update cgns version to 4.2.0

### PR DESCRIPTION
**Pull request by MicK7**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MicK7** [comment]
@conda-forge-admin, please rerender

**Review by mdpiper — APPROVED** [review]

**Comment by MicK7** [comment]
Can someone merge this topic ?
Thanks

**Comment by mdpiper** [comment]
@MicK7 Are you using CGNS? Would you like to be listed as a repository maintainer? Let me know & I'll open a separate PR. I'll merge this one.

**Comment by MicK7** [comment]
@mdpiper I am using CGNS (and pyCGNS too). Thanks for the proposal, I am not against being a maintainer as long as it does not take too much time (that should be the case for CGNS as there is only one release per year.)

**Pull request merged**
